Repository rk8s-dev/rk8s, pull requests merged in 2025-04, with the labels that each got.

#33 Update version of libfuse-fs BUCK
  project/libfuse-fs/BUCK
Labels: upgrade

#39 Add development guide
  docs/development.md
Labels: documentation

#41 GitHub Action 增加 buck2 构建和测试
  .github/install-sys-deps/action.yml
  .github/workflows/base.yml
  docs/development.md
Labels: r2cn, buck2

#42 Update Buck2 build config for libfuse-fs
  project/libfuse-fs/BUCK
  third-party/BUCK
  third-party/Cargo.toml
Labels: r2cn, buck2

#50 pass clippy check
  project/rkl/src/cli_commands.rs
  project/rkl/src/commands/create.rs
  project/rkl/src/commands/mod.rs
  project/rkl/src/cri/cri_api.rs
  project/rkl/src/cri/mod.rs
  project/rkl/src/main.rs
  project/rkl/src/task.rs
  project/rkl/src/task/mod.rs
  project/rkl/test/bundles/busybox/config.json
  project/rkl/test/pod-with-a-container.yaml
Labels: r2cn

#59 Supports CPU and memory resource limitations for containers
  project/rkl/README.md
  project/rkl/src/task.rs
  project/rkl/test/pod-with-a-container.yaml
Labels: good first issue, r2cn

#61 add exec function and some help infomation
  .buckconfig
  project/rkl/src/cli_commands.rs
  project/rkl/src/commands/exec.rs
  project/rkl/src/commands/exec_cli.rs
  project/rkl/src/commands/mod.rs
  project/rkl/src/main.rs
  project/rkl/test/bundles/busybox/config.json
  project/rkl/test/pod-with-a-container.yaml
Labels: r2cn

#58 Document: Add arch detection for Buck2 installation script
  docs/development.md
Labels: documentation
