Repository rk8s-dev/rk8s, pull requests merged in 2025-03, with the labels that each got.

#11 [Issue#7]增加使用 skopeo 转换镜像的文档
  docs/convert-docker-image-to-OCI-image-using-skopeo.md
Labels: documentation, r2cn

#12 实现 OCI Distribution Spec 主要功能
  project/distribution/.env.example
  project/distribution/.gitignore
  project/distribution/BUCK
  project/distribution/Cargo.toml
  project/distribution/README.md
  project/distribution/src/api/mod.rs
  project/distribution/src/api/v2.rs
  project/distribution/src/main.rs
  project/distribution/src/service/blob.rs
  project/distribution/src/service/manifest.rs
  project/distribution/src/service/mod.rs
  project/distribution/src/storage/driver/filesystem.rs
  project/distribution/src/storage/driver/mod.rs
  project/distribution/src/storage/mod.rs
  project/distribution/src/storage/paths.rs
  project/distribution/src/utils/cli.rs
  project/distribution/src/utils/mod.rs
  project/distribution/src/utils/state.rs
  project/distribution/src/utils/validation.rs
  third-party/BUCK
  third-party/Cargo.toml
  third-party/README.md
  third-party/fixups/axum/fixups.toml
  third-party/fixups/derive_builder_core/fixups.toml
  third-party/fixups/generic-array/fixups.toml
  third-party/fixups/oci-spec/fixups.toml
  third-party/fixups/rustversion/fixups.toml
  third-party/fixups/typenum/fixups.toml
  third-party/fixups/zerocopy/fixups.toml
Labels: r2cn

#29 Sync from youki resolve #28
  project/libcgroups/.gitignore copy
  project/libcgroups/Cargo.toml
  project/libcgroups/src/v1/memory.rs
  project/libcontainer/.gitignore
  project/libcontainer/Cargo.toml
  project/libcontainer/src/channel.rs
  project/libcontainer/src/container/tenant_builder.rs
  project/libcontainer/src/user_ns.rs
  project/tools/scripts/container_init_process.patch
  project/tools/scripts/sync_youki.sh
Labels: upgrade
